from PyQt5 import QtCore, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 180)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.manifestPathLayout = QtWidgets.QHBoxLayout()
        self.manifestPathLayout.setObjectName("manifestPathLayout")
        self.manifestPathEdit = QtWidgets.QLineEdit(Dialog)
        self.manifestPathEdit.setObjectName("manifestPathEdit")
        self.manifestPathEdit.setPlaceholderText("Path to manifest CSV")
        self.manifestPathLayout.addWidget(self.manifestPathEdit)
        self.manifestBrowseButton = QtWidgets.QPushButton(Dialog)
        self.manifestBrowseButton.setObjectName("manifestBrowseButton")
        self.manifestBrowseButton.setText("Browse...")
        self.manifestPathLayout.addWidget(self.manifestBrowseButton)
        self.reloadLocationsButton = QtWidgets.QPushButton(Dialog)
        self.reloadLocationsButton.setObjectName("reloadLocationsButton")
        self.reloadLocationsButton.setText("Reload Locations")
        self.manifestPathLayout.addWidget(self.reloadLocationsButton)
        self.verticalLayout.addLayout(self.manifestPathLayout)
        self.buildingsRadio = QtWidgets.QRadioButton(Dialog)
        self.buildingsRadio.setObjectName("buildingsRadio")
        self.buildingsRadio.setText("Buildings")
        self.buildingsRadio.setChecked(True)
        self.verticalLayout.addWidget(self.buildingsRadio)
        self.roadsRadio = QtWidgets.QRadioButton(Dialog)
        self.roadsRadio.setObjectName("roadsRadio")
        self.roadsRadio.setText("Roads")
        self.verticalLayout.addWidget(self.roadsRadio)
        self.locationComboBox = QtWidgets.QComboBox(Dialog)
        self.locationComboBox.setObjectName("locationComboBox")
        self.locationComboBox.addItem("Custom Area")
        self.verticalLayout.addWidget(self.locationComboBox)
        self.extentModeComboBox = QtWidgets.QComboBox(Dialog)
        self.extentModeComboBox.setObjectName("extentModeComboBox")
        self.extentModeComboBox.addItems(["Layer extent", "Canvas extent", "Draw custom area"])
        self.verticalLayout.addWidget(self.extentModeComboBox)
        self.drawExtentButton = QtWidgets.QPushButton(Dialog)
        self.drawExtentButton.setObjectName("drawExtentButton")
        self.drawExtentButton.setText("Draw Extent")
        self.verticalLayout.addWidget(self.drawExtentButton)
        self.selectRectangleButton = QtWidgets.QPushButton(Dialog)
        self.selectRectangleButton.setObjectName("selectRectangleButton")
        self.selectRectangleButton.setText("Select Area on Map")
        self.verticalLayout.addWidget(self.selectRectangleButton)
        self.extentLabel = QtWidgets.QLabel(Dialog)
        self.extentLabel.setObjectName("extentLabel")
        self.extentLabel.setText("")
        self.verticalLayout.addWidget(self.extentLabel)
        self.downloadButton = QtWidgets.QPushButton(Dialog)
        self.downloadButton.setObjectName("downloadButton")
        self.downloadButton.setText("Download")
        self.verticalLayout.addWidget(self.downloadButton)
        QtCore.QMetaObject.connectSlotsByName(Dialog) 